# Schema for the configuration files of the google_analytics module.

google_analytics.settings:
  type: mapping
  label: 'Google Analytics settings'
  mapping:
    account:
      type: string
      label: 'Web Property ID'
    domain_mode:
      type: integer
      label: 'What are you tracking?'
    cross_domains:
      type: string
      label: 'List of top-level domains'
    visibility:
      type: mapping
      label: 'Visibility'
      mapping:
        pages_enabled:
          type: integer
          label: 'Add tracking to specific pages'
        pages:
          type: string
          label: 'Pages by their paths'
        roles_enabled:
          type: integer
          label: 'Add tracking for specific roles'
        roles:
          type: array
          label: 'Roles'
        custom:
          type: integer
          label: 'Allow users to customize tracking on their account page'
    track:
      type: mapping
      label: 'Links and downloads'
      mapping:
        outbound:
          type: boolean
          label: 'Track clicks on outbound links'
        mailto:
          type: boolean
          label: 'Track clicks on mailto links'
        files:
          type: boolean
          label: 'Track downloads'
        files_extensions:
          type: string
          label: 'File extension list'
        linkid:
          type: boolean
          label: 'Enable enhanced link attribution'
        urlfragments:
          type: boolean
          label: 'Track changing URL fragments as pageviews'
        userid:
          type: boolean
          label: 'Track User ID'
        messages:
          type: array
          label: 'Track messages of type'
        site_search:
          type: boolean
          label: 'Track internal search'
        adsense:
          type: boolean
          label: 'Track AdSense ads'
        displayfeatures:
          type: boolean
          label: 'Track display features'
    privacy:
      type: mapping
      label: 'Privacy'
      mapping:
        anonymizeip:
          type: boolean
          label: 'Anonymize visitors IP address'
        donottrack:
          type: boolean
          label: 'Universal web tracking opt-out'
    custom:
      type: mapping
      label: 'Custom variables'
      mapping:
        dimension:
          type: array
          label: 'Custom dimensions'
        metric:
          type: array
          label: 'Custom metrics'
    codesnippet:
      type: mapping
      label: 'Custom code snippets'
      mapping:
        create:
          type: array
          label: 'Create only fields'
        before:
          type: string
          label: 'Code snippet (before)'
        after:
          type: string
          label: 'Code snippet (after)'
    translation_set:
      type: boolean
      label: 'Track translation sets as one unit'
    cache:
      type: boolean
      label: 'Locally cache tracking code file'
    debug:
      type: boolean
      label: 'Load debugging code of Google Universal Analytics'
